export const VIDEO = {
  SET_VIDEOS_DATA: "SET_VIDEOS_DATA",
  WATCH_LATER: "WATCH_LATER",
  NEW_PLAYLIST: "NEW_PLAYLIST",
  ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
  REMOVE_FROM_PLAYLIST: "REMOVE_FROM_PLAYLIST",
  ADD_NOTE: "ADD_NOTE",
  EDIT_NOTE: "EDIT_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  SEARCH: "SEARCH",
};
